### ISSUE TITLE
Is this an Obsidian plugin for Tiddlywiki?

### ISSUE THREAD

**Issue by anthrolisp** [tiddly-gittly/tidgi-obsidian-manager#31]
Is this an Obsidian plugin for Tiddlywiki?

**Comment by Zacharia2** [comment]
@anthrolisp Well, this is a TiddlyWiki version of the obsidian plugin. It can only be installed in TiddlyWiki, not obsidian.

**Comment by anthrolisp** [comment]
What does it do?

**Comment by anthrolisp** [comment]
How to use it? Does on need to run this in TidGi-Desktop?

**Comment by Zacharia2** [comment]
@anthrolisp It can import your ob vault into TiddlyWiki, using tidgi or the general nodejs version of TiddlyWiki as the usage environment. Drag and drop this plugin or install it using the cpl plugin library. After installation, you can find obm in the Control Panel - Settings. Then you can enter the path and click add to start the import. After the import, you can see the imported directory tree in the sidebar. Now you can choose whether to publish this wiki publicly or use it yourself.
